export const MAX_ATTACHMENT_FILES: 3;
export const DEFAULT_FILE_BYTES: number;
export const MAX_TURN_BYTES: number;
export const ATTACHMENT_ONLY_INPUT: string;
export type AttachmentFile = { fileId: string; name: string; ticket: string; size?: number };
export type AttachmentCapabilities = { enabled: boolean; maxFileBytes: number; maxFiles: number; maxTotalBytes: number };
export function isSafeFileName(value: unknown): value is string;
export function isFileId(value: unknown): value is string;
export function hasRetiredAttachment(source: string): boolean;
export function attachmentDisplayText(source: string, hideLocalPaths?: boolean): string;
export function formatFileSize(bytes?: number): string;
